//menu
!function(a,b){var d=function(a){return a.trim?a.trim():a.replace(/^\s+|\s+$/g,"")},e=function(a,b){return-1!==(" "+a.className+" ").indexOf(" "+b+" ")},f=function(a,b){e(a,b)||(a.className=""===a.className?b:a.className+" "+b)},g=function(a,b){a.className=d((" "+a.className+" ").replace(" "+b+" "," "))},h=function(a,b){if(a)do{if(a.id===b)return!0;if(9===a.nodeType)break}while(a=a.parentNode);return!1},i=b.documentElement,k=(a.Modernizr.prefixed("transform"),a.Modernizr.prefixed("transition")),l=function(){var a={WebkitTransition:"webkitTransitionEnd",MozTransition:"transitionend",OTransition:"oTransitionEnd otransitionend",msTransition:"MSTransitionEnd",transition:"transitionend"};return a.hasOwnProperty(k)?a[k]:!1}();a.App=function(){var c=!1,d={},j=b.getElementById("inner-wrap"),m=!1,n="js-nav";return d.init=function(){if(!c){c=!0;var o=function(a){a&&a.target===j&&b.removeEventListener(l,o,!1),m=!1};d.closeNav=function(){if(m){var c=l&&k?parseFloat(a.getComputedStyle(j,"")[k+"Duration"]):0;c>0?b.addEventListener(l,o,!1):o(null)}g(i,n)},d.openNav=function(){m||(f(i,n),m=!0)},d.toggleNav=function(a){m&&e(i,n)?d.closeNav():d.openNav(),a&&a.preventDefault()},b.getElementById("nav-open-btn").addEventListener("click",d.toggleNav,!1),b.addEventListener("click",function(a){m&&!h(a.target,"nav")&&(a.preventDefault(),d.closeNav())},!0),f(i,"js-ready")}},d}(),a.addEventListener&&a.addEventListener("DOMContentLoaded",a.App.init,!1)}(window,window.document);
//utilities
function getMatch(a, b) {
    var matches = [];

    for ( var i = 0; i < a.length; i++ ) {
        for ( var e = 0; e < b.length; e++ ) {
            if ( a[i] === b[e] ) matches.push( a[i] );
        }
    }
    return matches;
}


function shuffleArray(array) {
    for (var i = array.length - 1; i > 0; i--) {
        var j = Math.floor(Math.random() * (i + 1));
        var temp = array[i];
        array[i] = array[j];
        array[j] = temp;
    }
    return array;
}

'use strict';
var myApp = angular.module('myApp',[]);
myApp.controller('MainCtrl',['$scope',function ($scope) {
    $scope.tags = [
        {"key":"programming","name":"Programming Languages"},
        {"key":"js","name":"Javascript & stuff"},
        {"key":"misc","name":"Misc."},
        {"key":"browsers","name":"Browsers"},
        {"key":"useful","name":"Useful"},
        {"key":"tools","name":"Tools"},
        {"key":"html5","name":"HTML5 & stuff"},
        {"key":"css","name":"CSS & stuff"},
        {"key":"node","name":"Node.js & stuff"},
        {"key":"source","name":"Source control"},
        {"key":"social","name":"Social"},
        {"key":"os","name":"OS"},
        {"key":"frameworks","name":"Frameworks"},
        {"key":"resources","name":"Resources"},
        {"key":"companies","name":"Companies"},
        {"key":"ides","name":"IDEs"},
        {"key":"mob","name":"Mobile"},
        {"key":"websites","name":"Websites"},
        {"key":"cms","name":"CMS"},

    ];

    $scope.icons =[
                   {
                      "iconname":"git",
                      "key":"\\e602",
                      "desc":"",
                      "tags":[
                         "source",
                         "tools"
                      ]
                   },
                   {
                      "iconname":"git_compare",
                      "key":"\\e628",
                      "desc":"",
                      "tags":[
                         "source",
                         "tools"
                      ]
                   },
                   {
                      "iconname":"git_branch",
                      "key":"\\e625",
                      "desc":"",
                      "tags":[
                         "source",
                         "tools"
                      ]
                   },
                   {
                      "iconname":"git_commit",
                      "key":"\\e629",
                      "desc":"",
                      "tags":[
                         "source",
                         "tools"
                      ]
                   },
                   {
                      "iconname":"git_pull_request",
                      "key":"\\e626",
                      "desc":"",
                      "tags":[
                         "source",
                         "tools"
                      ]
                   },
                   {
                      "iconname":"git_merge",
                      "key":"\\e627",
                      "desc":"",
                      "tags":[
                         "source",
                         "tools"
                      ]
                   },
                   {
                      "iconname":"bitbucket",
                      "key":"\\e603",
                      "desc":"",
                      "tags":[
                         "source",
                         "tools",
                         "websites",
                         "social"
                      ]
                   },
                   {
                      "iconname":"github_alt",
                      "key":"\\e608",
                      "desc":"",
                      "tags":[
                         "source",
                         "tools",
                         "websites",
                         "social"
                      ]
                   },
                   {
                      "iconname":"github_badge",
                      "key":"\\e609",
                      "desc":"",
                      "tags":[
                         "source",
                         "tools",
                         "websites",
                         "social"
                      ]
                   },
                   {
                      "iconname":"github",
                      "key":"\\e60a",
                      "desc":"",
                      "tags":[
                         "source",
                         "tools",
                         "websites",
                         "social"
                      ]
                   },
                   {
                      "iconname":"github_full",
                      "key":"\\e617",
                      "desc":"",
                      "tags":[
                         "source",
                         "tools",
                         "websites",
                         "social"
                      ]
                   },

                   
                   
                   {
                      "iconname":"trello",
                      "key":"\\e65a",
                      "desc":"",
                      "tags":[
                         "tools",
                         "misc"
                      ]
                   },
                   {
                      "iconname":"atlassian",
                      "key":"\\e65b",
                      "desc":"",
                      "tags":[
                         "companies",
                         "websites",
                         "resources"
                      ]
                   },
                   {
                      "iconname":"jira",
                      "key":"\\e65c",
                      "desc":"",
                      "tags":[
                         "source",
                         "tools",
                         "misc"
                      ]
                   },
                   {
                      "iconname":"java",
                      "key":"\\e638",
                      "desc":"",
                      "tags":[
                         "programming"
                      ]
                   },
                   {
                      "iconname":"ruby",
                      "key":"\\e639",
                      "desc":"",
                      "tags":[
                         "programming"
                      ]
                   },
                   {
                      "iconname":"scala",
                      "key":"\\e637",
                      "desc":"",
                      "tags":[
                         "programming"
                      ]
                   },
                   {
                      "iconname":"python",
                      "key":"\\e63c",
                      "desc":"",
                      "tags":[
                         "programming"
                      ]
                   },
                   {
                      "iconname":"go",
                      "key":"\\e624",
                      "desc":"",
                      "tags":[
                         "programming"
                      ]
                   },
                   {
                      "iconname":"ruby_on_rails",
                      "key":"\\e63b",
                      "desc":"",
                      "tags":[
                         "frameworks",
                         "programming"
                      ]
                   },
                   {
                      "iconname":"django",
                      "key":"\\e61d",
                      "desc":"",
                      "tags":[
                         "frameworks",
                         "programming"
                      ]
                   },
                   {
                      "iconname":"markdown",
                      "key":"\\e63e",
                      "desc":"",
                      "tags":[
                         "programming",
                         "frameworks"
                      ]
                   },
                   {
                      "iconname":"php",
                      "key":"\\e63d",
                      "desc":"",
                      "tags":[
                         "programming"
                      ]
                   },
                   {
                      "iconname":"symfony",
                      "key":"\\e656",
                      "desc":"",
                      "tags":[
                         "frameworks",
                         "tools"
                      ]
                   },
                   {
                      "iconname":"symfony_badge",
                      "key":"\\e657",
                      "desc":"",
                      "tags":[
                         "frameworks",
                         "tools"
                      ]
                   },
                   {
                      "iconname":"mysql",
                      "key":"\\e604",
                      "desc":"",
                      "tags":[
                         "tools",
                         "programming"
                      ]
                   },
                   {
                      "iconname":"streamline",
                      "key":"\\e605",
                      "desc":"",
                      "tags":[
                         "tools",
                         "programming",
                         "misc"
                      ]
                   },
                   {
                      "iconname":"database",
                      "key":"\\e606",
                      "desc":"",
                      "tags":[
                         "tools",
                         "programming",
                         "misc"
                      ]
                   },
                   {
                      "iconname":"laravel",
                      "key":"\\e63f",
                      "desc":"",
                      "tags":[
                         "programming",
                         "frameworks"
                      ]
                   },
                   {
                      "iconname":"javascript",
                      "key":"\\e64e",
                      "desc":"",
                      "tags":[
                         "tools",
                         "programming",
                         "node",
                         "frameworks",
                         "js"
                      ]
                   },
                   {
                      "iconname":"angular",
                      "key":"\\e653",
                      "desc":"",
                      "tags":[
                         "js",
                         "frameworks"
                      ]
                   },
                   {
                      "iconname":"backbone",
                      "key":"\\e652",
                      "desc":"",
                      "tags":[
                         "js",
                         "frameworks"
                      ]
                   },
                   {
                      "iconname":"snap_svg",
                      "key":"\\e65e",
                      "desc":"",
                      "tags":[
                         "js",
                         "frameworks"
                      ]
                   },
                   {
                      "iconname":"raphael",
                      "key":"\\e65f",
                      "desc":"",
                      "tags":[
                         "js",
                         "frameworks"
                      ]
                   },
                   {
                      "iconname":"coffeescript",
                      "key":"\\e651",
                      "desc":"",
                      "tags":[
                         "js",
                         "frameworks"
                      ]
                   },
                   {
                      "iconname":"jquery",
                      "key":"\\e650",
                      "desc":"",
                      "tags":[
                         "js",
                         "frameworks"
                      ]
                   },
                   {
                      "iconname":"modernizr",
                      "key":"\\e620",
                      "desc":"",
                      "tags":{

                      }
                   },
                   {
                      "iconname":"jquery_ui",
                      "key":"\\e654",
                      "desc":"",
                      "tags":[
                         "js",
                         "frameworks"
                      ]
                   },
                   {
                      "iconname":"ember",
                      "key":"\\e61b",
                      "desc":"",
                      "tags":[
                         "js",
                         "frameworks"
                      ]
                   },
                   {
                      "iconname":"dojo",
                      "key":"\\e61c",
                      "desc":"",
                      "tags":[
                         "js",
                         "frameworks"
                      ]
                   },
                   {
                      "iconname":"nodejs",
                      "key":"\\e619",
                      "desc":"",
                      "tags":[
                         "js",
                         "frameworks"
                      ]
                   },
                   {
                      "iconname":"nodejs_small",
                      "key":"\\e618",
                      "desc":"",
                      "tags":[
                         "tools",
                         "programming",
                         "node",
                         "frameworks"
                      ]
                   },
                   {
                      "iconname":"javascript_shield",
                      "key":"\\e64f",
                      "desc":"",
                      "tags":[
                         "tools",
                         "programming",
                         "node",
                         "frameworks",
                         "js"
                      ]
                   },
                   {
                      "iconname":"bootstrap",
                      "key":"\\e647",
                      "desc":"",
                      "tags":[
                         "css",
                         "frameworks"
                      ]
                   },
                   {
                      "iconname":"sass",
                      "key":"\\e64b",
                      "desc":"",
                      "tags":[
                         "css",
                         "frameworks",
                         "tools"
                      ]
                   },
                   {
                      "iconname":"compass",
                      "key":"\\e661",
                      "desc":"",
                      "tags":[
                         "css",
                         "frameworks",
                         "tools"
                      ]
                   },
                   {
                      "iconname":"less",
                      "key":"\\e658",
                      "desc":"",
                      "tags":[
                         "css",
                         "frameworks",
                         "tools"
                      ]
                   },
                   {
                      "iconname":"stylus",
                      "key":"\\e659",
                      "desc":"",
                      "tags":[
                         "css",
                         "frameworks",
                         "tools"
                      ]
                   },
                   {
                      "iconname":"css3_full",
                      "key":"\\e64a",
                      "desc":"",
                      "tags":[
                         "css",
                         "html5"
                      ]
                   },
                   {
                      "iconname":"css3",
                      "key":"\\e649",
                      "desc":"",
                      "tags":[
                         "css",
                         "html5"
                      ]
                   },
                   {
                      "iconname":"html5",
                      "key":"\\e636",
                      "desc":"",
                      "tags":[
                         "html5"
                      ]
                   },
                   {
                      "iconname":"html5_multimedia",
                      "key":"\\e632",
                      "desc":"",
                      "tags":[
                         "html5"
                      ]
                   },
                   {
                      "iconname":"html5_device_access",
                      "key":"\\e633",
                      "desc":"",
                      "tags":[
                         "html5"
                      ]
                   },
                   {
                      "iconname":"html5_3d_effects",
                      "key":"\\e635",
                      "desc":"",
                      "tags":[
                         "html5"
                      ]
                   },
                   {
                      "iconname":"html5_connectivity",
                      "key":"\\e634",
                      "desc":"",
                      "tags":[
                         "html5"
                      ]
                   },
                   {
                      "iconname":"ghost_small",
                      "key":"\\e614",
                      "desc":"",
                      "tags":[
                         "tools",
                         "cms"
                      ]
                   },
                   {
                      "iconname":"ghost",
                      "key":"\\e61f",
                      "desc":"",
                      "tags":[
                         "tools",
                         "cms"
                      ]
                   },
                   {
                      "iconname":"magento",
                      "key":"\\e640",
                      "desc":"",
                      "tags":[
                         "tools",
                         "cms"
                      ]
                   },
                   {
                      "iconname":"joomla",
                      "key":"\\e641",
                      "desc":"",
                      "tags":[
                         "tools",
                         "cms"
                      ]
                   },
                   {
                      "iconname":"jekyll_small",
                      "key":"\\e60d",
                      "desc":"",
                      "tags":[
                         "tools",
                         "cms"
                      ]
                   },
                   {
                      "iconname":"drupal",
                      "key":"\\e642",
                      "desc":"",
                      "tags":[
                         "tools",
                         "cms"
                      ]
                   },
                   {
                      "iconname":"wordpress",
                      "key":"\\e60b",
                      "desc":"",
                      "tags":[
                         "tools",
                         "cms"
                      ]
                   },
                   {
                      "iconname":"grunt",
                      "key":"\\e64c",
                      "desc":"",
                      "tags":[
                         "tools",
                         "node"
                      ]
                   },
                   {
                      "iconname":"bower",
                      "key":"\\e64d",
                      "desc":"",
                      "tags":[
                         "tools",
                         "node"
                      ]
                   },
                   {
                      "iconname":"gulp",
                      "key":"\\e663",
                      "desc":"",
                      "tags":[
                         "tools",
                         "js"
                      ]
                   },
                   {
                      "iconname":"npm",
                      "key":"\\e61e",
                      "desc":"",
                      "tags":[
                         "tools",
                         "node"
                      ]
                   },
                   {
                      "iconname":"yahoo_small",
                      "key":"\\e62b",
                      "desc":"",
                      "tags":[
                         "websites",
                         "resources",
                         "companies",
                         "useful"
                      ]
                   },

                   {
                      "iconname":"yahoo",
                      "key":"\\e615",
                      "desc":"",
                      "tags":[
                         "websites",
                         "resources",
                         "companies",
                         "useful"
                      ]
                   },
                   {
                      "iconname":"bing_small",
                      "key":"\\e600",
                      "desc":"",
                      "tags":[
                         "websites",
                         "resources",
                         "companies",
                         "useful"
                      ]
                   },
                   {
                      "iconname":"cisco",
                      "key":"\\e665",
                      "desc":"",
                      "tags":[
                         "companies",
                         "misc"
                      ]
                   },
                   {
                      "iconname":"windows",
                      "key":"\\e60f",
                      "desc":"",
                      "tags":[
                         "os",
                         "companies"
                      ]
                   },
                   {
                      "iconname":"linux",
                      "key":"\\e612",
                      "desc":"",
                      "tags":[
                         "os",
                         "companies"
                      ]
                   },
                   {
                      "iconname":"ubuntu",
                      "key":"\\e63a",
                      "desc":"",
                      "tags":[
                         "os",
                         "companies"
                      ]
                   },
                   {
                      "iconname":"android",
                      "key":"\\e60e",
                      "desc":"",
                      "tags":[
                         "os",
                         "companies"
                      ]
                   },
                   {
                      "iconname":"apple",
                      "key":"\\e611",
                      "desc":"",
                      "tags":{

                      }
                   },
                   {
                      "iconname":"appstore",
                      "key":"\\e613",
                      "desc":"",
                      "tags":[
                         "os",
                         "companies"
                      ]
                   },
                   {
                      "iconname":"phonegap",
                      "key":"\\e630",
                      "desc":"",
                      "tags":[
                         "mob",
                         "misc"
                      ]
                   },
                   {
                      "iconname":"swift",
                      "key":"\\e655",
                      "desc":"",
                      "tags":[
                         "programming","mob"
                      ]
                   },
                   {
                      "iconname":"blackberry",
                      "key":"\\e623",
                      "desc":"",
                      "tags":[
                         "mob",
                         "misc"
                      ]
                   },
                   {
                      "iconname":"stackoverflow",
                      "key":"\\e610",
                      "desc":"",
                      "tags":[
                         "websites",
                         "resources"
                      ]
                   },
                   {
                      "iconname":"techcrunch",
                      "key":"\\e62c",
                      "desc":"",
                      "tags":[
                         "websites",
                         "resources"
                      ]
                   },
                   {
                      "iconname":"codrops",
                      "key":"\\e62f",
                      "desc":"",
                      "tags":[
                         "websites",
                         "resources"
                      ]
                   },
                   {
                      "iconname":"css_tricks",
                      "key":"\\e601",
                      "desc":"",
                      "tags":[
                         "websites",
                         "resources"
                      ]
                   },

                   {
                      "iconname":"envato",
                      "key":"\\e65d",
                      "desc":"",
                      "tags":[
                         "resources",
                         "tools",
                         "misc",
                         "useful"
                      ]
                   },
                   {
                      "iconname":"smashing_magazine",
                      "key":"\\e62d",
                      "desc":"",
                      "tags":[
                         "websites",
                         "resources"
                      ]
                   },
                   {
                      "iconname":"netmagazine",
                      "key":"\\e62e",
                      "desc":"",
                      "tags":[
                         "websites",
                         "resources"
                      ]
                   },
                   {
                      "iconname":"codepen",
                      "key":"\\e616",
                      "desc":"",
                      "tags":[
                         "websites",
                         "resources",
                         "useful",
                         "social"
                      ]
                   },
                   {
                      "iconname":"cssdeck",
                      "key":"\\e62a",
                      "desc":"",
                      "tags":[
                         "websites",
                         "resources",
                         "useful",
                         "social"
                      ]
                   },
                   {
                      "iconname":"hackers",
                      "key":"\\e61a",
                      "desc":"",
                      "tags":[
                         "websites",
                         "resources",
                         "useful",
                         "social"
                      ]
                   },
                   {
                      "iconname":"dropbox",
                      "key":"\\e607",
                      "desc":"",
                      "tags":[
                         "tools"
                      ]
                   },
                   {
                      "iconname":"onedrive",
                      "key":"\\e662",
                      "desc":"",
                      "tags":[
                         "tools"
                      ]
                   },
                   {
                      "iconname":"google_drive",
                      "key":"\\e631",
                      "desc":"",
                      "tags":[
                         "tools"
                      ]
                   },
                   {
                      "iconname":"visualstudio",
                      "key":"\\e60c",
                      "desc":"",
                      "tags":[
                         "tools",
                         "ides"
                      ]
                   },
                   {
                      "iconname":"atom",
                      "key":"\\e664",
                      "desc":"",
                      "tags":[
                         "tools",
                         "ides"
                      ]
                   },
                   {
                      "iconname":"unity_small",
                      "key":"\\e621",
                      "desc":"",
                      "tags":[
                         "tools",
                         "frameworks",
                         "misc"
                      ]
                   },
                   {
                      "iconname":"rasberry_pi",
                      "key":"\\e622",
                      "desc":"",
                      "tags":[
                         "misc"
                      ]
                   },
                   {
                      "iconname":"chrome",
                      "key":"\\e643",
                      "desc":"",
                      "tags":[
                         "browsers"
                      ]
                   },
                   {
                      "iconname":"ie",
                      "key":"\\e644",
                      "desc":"",
                      "tags":[
                         "browsers"
                      ]
                   },
                   {
                      "iconname":"firefox",
                      "key":"\\e645",
                      "desc":"",
                      "tags":[
                         "browsers"
                      ]
                   },
                   {
                      "iconname":"opera",
                      "key":"\\e646",
                      "desc":"",
                      "tags":[
                         "browsers"
                      ]
                   },
                   {
                      "iconname":"safari",
                      "key":"\\e648",
                      "desc":"",
                      "tags":[
                         "browsers"
                      ]
                   },
                    {"iconname":"nancy","key":"\\e666","desc":"","tags":["tools","useful","frameworks"]},
                    {"iconname":"clojure","key":"\\e668","desc":"","tags":["frameworks"]},
                    {"iconname":"clojure_alt","key":"\\e66a","desc":"","tags":["frameworks"]},
                    {"iconname":"perl","key":"\\e669","desc":"","tags":["programming"]},
                    {"iconname":"celluloid","key":"\\e66b","desc":"","tags":["frameworks"]},
                    {"iconname":"w3c","key":"\\e66c","desc":"","tags":["useful","resources"]},
                    {"iconname":"redis","key":"\\e66d","desc":"","tags":["tools","programming"]},
                    {"iconname":"postgresql","key":"\\e66e","desc":"","tags":["tools","programming"]},
                    {"iconname":"webplatform","key":"\\e66f","desc":"","tags":["useful","resources"]},
                    {"iconname":"jenkins","key":"\\e667","desc":"","tags":["frameworks","tools","misc"]}
                    ,{"iconname":"requirejs","key":"\\e670","desc":"new","tags":["js","frameworks"]},
                    {"iconname":"opensource","key":"\\e671","desc":"new","tags":["misc"]},
                    {"iconname":"typo3","key":"\\e672","desc":"new","tags":["cms"]},
                    {"iconname":"uikit","key":"\\e673","desc":"new","tags":["frameworks","tools","misc"]},
                    {"iconname":"doctrine","key":"\\e674","desc":"new","tags":["frameworks","tools","misc"]},
                    {"iconname":"groovy","key":"\\e675","desc":"new","tags":["tools","useful"] },
                    {"iconname":"ngnix","key":"\\e676","desc":"new","tags":["tools","useful"] },
                    {"iconname":"haskell","key":"\\e677","desc":"new","tags":["programming"]},
                    {"iconname":"zend","key":"\\e678","desc":"new","tags":["frameworks"]},
                    {"iconname":"gnu","key":"\\e679","desc":"new","tags":["misc"]},
                    {"iconname":"yeoman","key":"\\e67a","desc":"new","tags":["tools","useful"]},
                    {"iconname":"heroku","key":"\\e67b","desc":"new","tags":["tools","useful"] }
                ];
    $scope.filteredIcons = [];
    $scope.active = false;


   $scope.randomIcons=$scope.icons;

$scope.includeInFilter = function(tag) {
        var i = $.inArray(tag, $scope.filteredIcons);
        if (i > -1) {
            $scope.filteredIcons.splice(i, 1);
        } else {
            $scope.filteredIcons.push(tag);
        }
    }

$scope.filterTheIcons = function(icon) {
        
        var matched;
        if ($scope.filteredIcons.length > 0) {
            matched=getMatch(icon.tags,$scope.filteredIcons);
            if ( !matched.length > 0)
                return;
        }
        
        return icon;
    }
  $(".overlay").fadeOut('slow');
}]);    


jQuery(document).ready(function($) {
   var lastId,
    topMenu = $("nav"),
    topMenuHeight = topMenu.outerHeight()+15,
    // All list items
    menuItems = topMenu.find("a"),
    // Anchors corresponding to menu items
    scrollItems = menuItems.map(function(){
      var item = $($(this).attr("href"));
      if (item.length) { return item; }
    });
    menuItems.click(function(e){
      var href = $(this).attr("href"),
          offsetTop = href === "#" ? 0 : $(href).offset().top-topMenuHeight+1;
      $('html, body').stop().animate({ 
          scrollTop: offsetTop
      }, 300);
      e.preventDefault();
    });
   function fix_scroll() {
     var s = $(window).scrollTop();
     var fixedHeader = $('header');
     fixedHeader.css('position','absolute');
     fixedHeader.css('top',s + 'px');

     var fixedMenu = $('#nav');
     fixedMenu.css('position','absolute');
     fixedMenu.css('top',s + 'px');
     
   }fix_scroll();

   function naved(){
         // Get container scroll position
       var fromTop = $(this).scrollTop()+topMenuHeight;
       
       // Get id of current scroll item
       var cur = scrollItems.map(function(){
         if ($(this).offset().top < fromTop)
           return this;
       });
       // Get the id of the current element
       cur = cur[cur.length-1];
       var id = cur && cur.length ? cur[0].id : "";
       
       if (lastId !== id) {
           lastId = id;
           // Set/remove active class
           menuItems
             .parent().removeClass("active")
             .end().filter("[href=#"+id+"]").parent().addClass("active");
       }  
   }
   $(window).on('scroll',function(){ fix_scroll(); naved(); });
});



