/* To avoid CSS expressions while still supporting IE 7 and IE 6, use this script */
/* The script tag referring to this file must be placed before the ending body tag. */

/* Use conditional comments in order to target IE 7 and older:
	<!--[if lt IE 8]><!-->
	<script src="ie7/ie7.js"></script>
	<!--<![endif]-->
*/

(function() {
	function addIcon(el, entity) {
		var html = el.innerHTML;
		el.innerHTML = '<span style="font-family: \'devicons\'">' + entity + '</span>' + html;
	}
	var icons = {
		'devicons-git': '&#xe602;',
		'devicons-git_compare': '&#xe628;',
		'devicons-git_branch': '&#xe625;',
		'devicons-git_commit': '&#xe629;',
		'devicons-git_pull_request': '&#xe626;',
		'devicons-git_merge': '&#xe627;',
		'devicons-bitbucket': '&#xe603;',
		'devicons-github_alt': '&#xe608;',
		'devicons-github_badge': '&#xe609;',
		'devicons-github': '&#xe60a;',
		'devicons-github_full': '&#xe617;',
		'devicons-java': '&#xe638;',
		'devicons-ruby': '&#xe639;',
		'devicons-scala': '&#xe637;',
		'devicons-python': '&#xe63c;',
		'devicons-go': '&#xe624;',
		'devicons-ruby_on_rails': '&#xe63b;',
		'devicons-django': '&#xe61d;',
		'devicons-markdown': '&#xe63e;',
		'devicons-php': '&#xe63d;',
		'devicons-mysql': '&#xe604;',
		'devicons-streamline': '&#xe605;',
		'devicons-database': '&#xe606;',
		'devicons-laravel': '&#xe63f;',
		'devicons-javascript': '&#xe64e;',
		'devicons-angular': '&#xe653;',
		'devicons-backbone': '&#xe652;',
		'devicons-coffeescript': '&#xe651;',
		'devicons-jquery': '&#xe650;',
		'devicons-modernizr': '&#xe620;',
		'devicons-jquery_ui': '&#xe654;',
		'devicons-ember': '&#xe61b;',
		'devicons-dojo': '&#xe61c;',
		'devicons-nodejs': '&#xe619;',
		'devicons-nodejs_small': '&#xe618;',
		'devicons-javascript_shield': '&#xe64f;',
		'devicons-bootstrap': '&#xe647;',
		'devicons-sass': '&#xe64b;',
		'devicons-css3_full': '&#xe64a;',
		'devicons-css3': '&#xe649;',
		'devicons-html5': '&#xe636;',
		'devicons-html5_multimedia': '&#xe632;',
		'devicons-html5_device_access': '&#xe633;',
		'devicons-html5_3d_effects': '&#xe635;',
		'devicons-html5_connectivity': '&#xe634;',
		'devicons-ghost_small': '&#xe614;',
		'devicons-ghost': '&#xe61f;',
		'devicons-magento': '&#xe640;',
		'devicons-joomla': '&#xe641;',
		'devicons-jekyll_small': '&#xe60d;',
		'devicons-drupal': '&#xe642;',
		'devicons-wordpress': '&#xe60b;',
		'devicons-grunt': '&#xe64c;',
		'devicons-bower': '&#xe64d;',
		'devicons-npm': '&#xe61e;',
		'devicons-yahoo_small': '&#xe62b;',
		'devicons-yahoo': '&#xe615;',
		'devicons-bing_small': '&#xe600;',
		'devicons-windows': '&#xe60f;',
		'devicons-linux': '&#xe612;',
		'devicons-ubuntu': '&#xe63a;',
		'devicons-android': '&#xe60e;',
		'devicons-apple': '&#xe611;',
		'devicons-appstore': '&#xe613;',
		'devicons-phonegap': '&#xe630;',
		'devicons-blackberry': '&#xe623;',
		'devicons-stackoverflow': '&#xe610;',
		'devicons-techcrunch': '&#xe62c;',
		'devicons-codrops': '&#xe62f;',
		'devicons-css_tricks': '&#xe601;',
		'devicons-smashing_magazine': '&#xe62d;',
		'devicons-netmagazine': '&#xe62e;',
		'devicons-codepen': '&#xe616;',
		'devicons-cssdeck': '&#xe62a;',
		'devicons-hackernews': '&#xe61a;',
		'devicons-dropbox': '&#xe607;',
		'devicons-google_drive': '&#xe631;',
		'devicons-visualstudio': '&#xe60c;',
		'devicons-unity_small': '&#xe621;',
		'devicons-rasberry_pi': '&#xe622;',
		'devicons-chrome': '&#xe643;',
		'devicons-ie': '&#xe644;',
		'devicons-firefox': '&#xe645;',
		'devicons-opera': '&#xe646;',
		'devicons-safari': '&#xe648;',
		'devicons-swift': '&#xe655;',
		'devicons-symfony': '&#xe656;',
		'devicons-symfony_badge': '&#xe657;',
		'devicons-less': '&#xe658;',
		'devicons-stylus': '&#xe659;',
		'devicons-trello': '&#xe65a;',
		'devicons-atlassian': '&#xe65b;',
		'devicons-jira': '&#xe65c;',
		'devicons-envato': '&#xe65d;',
		'devicons-snap_svg': '&#xe65e;',
		'devicons-raphael': '&#xe65f;',
		'devicons-google_analytics': '&#xe660;',
		'devicons-compass': '&#xe661;',
		'devicons-onedrive': '&#xe662;',
		'devicons-gulp': '&#xe663;',
		'devicons-atom': '&#xe664;',
		'devicons-cisco': '&#xe665;',
		'devicons-nancy': '&#xe666;',
		'devicons-clojure': '&#xe668;',
		'devicons-clojure_alt': '&#xe66a;',
		'devicons-perl': '&#xe669;',
		'devicons-celluloid': '&#xe66b;',
		'devicons-w3c': '&#xe66c;',
		'devicons-redis': '&#xe66d;',
		'devicons-postgresql': '&#xe66e;',
		'devicons-webplatform': '&#xe66f;',
		'devicons-jenkins': '&#xe667;',
		'devicons-requirejs': '&#xe670;',
		'devicons-opensource': '&#xe671;',
		'devicons-typo3': '&#xe672;',
		'devicons-uikit': '&#xe673;',
		'devicons-doctrine': '&#xe674;',
		'devicons-groovy': '&#xe675;',
		'devicons-nginx': '&#xe676;',
		'devicons-haskell': '&#xe677;',
		'devicons-zend': '&#xe678;',
		'devicons-gnu': '&#xe679;',
		'devicons-yeoman': '&#xe67a;',
		'devicons-heroku': '&#xe67b;',
		'devicons-debian': '&#xe67d;',
		'devicons-travis': '&#xe67e;',
		'devicons-dotnet': '&#xe67f;',
		'devicons-codeigniter': '&#xe680;',
		'devicons-javascript_badge': '&#xe681;',
		'devicons-yii': '&#xe682;',
		'devicons-msql_server': '&#xe67c;',
		'devicons-composer': '&#xe683;',
		'devicons-krakenjs_badge': '&#xe684;',
		'devicons-krakenjs': '&#xe685;',
		'devicons-mozilla': '&#xe686;',
		'devicons-firebase': '&#xe687;',
		'devicons-sizzlejs': '&#xe688;',
		'devicons-creativecommons': '&#xe689;',
		'devicons-creativecommons_badge': '&#xe68a;',
		'devicons-mitlicence': '&#xe68b;',
		'devicons-senchatouch': '&#xe68c;',
		'devicons-bugsense': '&#xe68d;',
		'devicons-extjs': '&#xe68e;',
		'devicons-mootools_badge': '&#xe68f;',
		'devicons-mootools': '&#xe690;',
		'devicons-ruby_rough': '&#xe691;',
		'devicons-komodo': '&#xe692;',
		'devicons-coda': '&#xe693;',
		'devicons-bintray': '&#xe694;',
		'devicons-terminal': '&#xe695;',
		'devicons-code': '&#xe696;',
		'devicons-responsive': '&#xe697;',
		'devicons-dart': '&#xe698;',
		'devicons-aptana': '&#xe699;',
		'devicons-mailchimp': '&#xe69a;',
		'devicons-netbeans': '&#xe69b;',
		'devicons-dreamweaver': '&#xe69c;',
		'devicons-brackets': '&#xe69d;',
		'devicons-eclipse': '&#xe69e;',
		'devicons-cloud9': '&#xe69f;',
		'devicons-scrum': '&#xe6a0;',
		'devicons-prolog': '&#xe6a1;',
		'devicons-terminal_badge': '&#xe6a2;',
		'devicons-code_badge': '&#xe6a3;',
		'devicons-mongodb': '&#xe6a4;',
		'0': 0
		},
		els = document.getElementsByTagName('*'),
		i, c, el;
	for (i = 0; ; i += 1) {
		el = els[i];
		if(!el) {
			break;
		}
		c = el.className;
		c = c.match(/devicons-[^\s'"]+/);
		if (c && icons[c[0]]) {
			addIcon(el, icons[c[0]]);
		}
	}
}());
